use_frameworks!

platform :ios, '9.0'

target 'BaseConfig_Example' do
  pod 'BaseConfig', :path => '../'

  target 'BaseConfig_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
